# KafkaConnect with integrated Debezium Connectors: PostgreSQL, MySQL
#
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-db-cluster
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.8.0
  replicas: 1
  bootstrapServers: broker-kafka-bootstrap.strimzi-test:9093
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/strimzi-test/kafka-connect-postgresql-cluster:latest
      #pushSecret: my-registry-credentials
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.7.0.Final/debezium-connector-postgres-1.7.0.Final-plugin.tar.gz
            sha512sum: 8aeeab767e9085b8fc034273c08ac6dc501b96ebb970634e45bdd81e51c6dd66b1b02a481990a6196cb6b89fe9f52b823bda7b74d3994f72bb3d9b9d507ab2b5
      - name: debezium-mysql-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.7.0.Final/debezium-connector-mysql-1.7.0.Final-plugin.tar.gz
            sha512sum: d2ad1c1adacb9121eae48b163a4af141261af7d456a837901ceb38f67bf43b274e6ad2effa08ad3b9d8eb7151ca2766770d39744ef063d03baa31cb7420a1cd4
      - name: groovy
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar
      - name: groovy-jsr223
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-jsr223/3.0.9/groovy-jsr223-3.0.9.jar
      - name: debezium-smt-scripting
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-scripting/1.7.0.Final/debezium-scripting-1.7.0.Final.tar.gz
            sha512sum: 360b48349ab7da6b68f91fb77eac7020989abeb756f9893a1c83d3ccd8872ef7d8b2a284cbfdcc8374bfc8cd5366ee1c74e7930cf4de331ed922fe78cf59df82
  # Set refernce to the secret of Kafka Broker, which was created by the Strimzi installation 
  # check the namespace where the Kafka Broker is running
  tls:
    trustedCertificates:
      - secretName: broker-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
